### ISSUE TITLE
Configurable Menu Structure

### ISSUE THREAD

**Issue by ziyan-junaideen** [ziyan-junaideen/consul#1]
### User Story

As an admin user, I want to be able to add menu items before and after the main navigation. The `top_links` navigation would hide if a content block is present for the section. 

### Why is this Needed?

Currently the main menu is static. We would require the ability to add links to left and right of the main menu.

In addition, the top links section should hide should a content_block be available for the location.

### Description

*Type*: Feature

2 new content_block zones (identified as 2a, 2b in the image below) to be introduced. They will be used to add custom navigation links to the menu.

The top links will hide should a content block be defined for that location.

![consul for pbp wireframing](https://user-images.githubusercontent.com/762159/42814067-b11bc3f2-89e0-11e8-9a76-95de2c54ba9b.jpg)

### Current Behavior

The main navigation is static. The top links section hides the blog link if it doesn't have one. The transparency and opendata links are always shown.

### Expected Behavior

- Ability to add navigation links to the main navigation (before and after)
- The top links section to hide and show only the content block for the location should it have a content block.

**Comment by ziyan-junaideen** [comment]
@devinbalkind would we want another field for some thing like ('open in a new window') ?

**Comment by devinbalkind** [comment]
Yes, please add that. Thanks!
