### ISSUE TITLE
ExecJS::RuntimeError

### ISSUE THREAD

**Issue by allthesignals** [ziyan-junaideen/consul#6]
During deployment, I'm seeing this after attempting to precompile assets:

`ExecJS::RuntimeError:`

Any thoughts? I am trying to deploy the latest commits.

**Comment by ziyan-junaideen** [comment]
Sorry I didn't see this...
Exec JS requires one backed to compile, install nodejs and you should be fine...
Heroku how ever shouldn't have this issue... because it detects the rails build pack on first deploy

**Comment by allthesignals** [comment]
No longer an issue since we moved to heroku. Thanks!
